services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # RabbitMQ port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: ./../.
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      SMTP_SERVER: smtp.mailtrap.live
      SMTP_PORT: 2525
      SMTP_USERNAME: b0a994e5c7e9bb
      SMTP_PASSWORD: 0cefabf913bf5b
    restart: always
